# -*- mode: ruby -*-
# vi: set ft=ruby :

# now support centOS 6.6 to 7.7
IMAGE_NAME = "generic/centos7"
IMAGE_VERSION = "3.0.10"

# Vagrantfile for centOS
Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.vm.box_version = IMAGE_VERSION
  config.vm.provision :shell, path: "provision.sh", privileged: false

  # data nodes
  (1..1).each do |i|
    config.vm.define "data#{i}" do |data_config|
      data_config.vm.provider "virtualbox" do |vb|
        vb.memory = 1536
        vb.cpus = 1
      end

      data_config.vm.hostname = "data#{i}"
      data_config.vm.network "private_network", ip: "172.20.21.3#{i}"
    end
  end

  # master node
  config.vm.define "master", primary: true do |master_config|
    # at least 4GB, otherwise kibana launch will get stuck
    master_config.vm.provider "virtualbox" do |vb|
      vb.memory = 3072
      vb.cpus = 2
    end

    master_config.vm.hostname = "master"
    master_config.vm.network "private_network", ip: "172.20.21.30"
  end
end
