# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box link: https://portal.cloud.hashicorp.com/vagrant/discover/bento/rockylinux-9
IMAGE_NAME = "bento/rockylinux-9"
IMAGE_VERSION = "202502.21.0"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.vm.box_version = IMAGE_VERSION

  # I disabled the synced folder as the rocky linux image does not have
  # VirtualBox Guest Additions installed, this shared folder feature is not
  # necessary to run VM.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ES data nodes
  (1..1).each do |i|
    config.vm.define "data#{i}" do |data_config|
      data_config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end

      data_config.vm.hostname = "data#{i}"
      data_config.vm.network "private_network", ip: "172.20.21.3#{i}"
      data_config.vm.provision :shell, path: "provision-elasticsearch-kibana.sh", privileged: false
    end
  end

  # ES master node
  config.vm.define "master", primary: true do |master_config|
    # at least 4GB, otherwise kibana launch will get stuck
    master_config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
    end

    master_config.vm.hostname = "master"
    master_config.vm.network "private_network", ip: "172.20.21.30"
    master_config.vm.provision :shell, path: "provision-elasticsearch-kibana.sh", privileged: false
  end

  # client
  config.vm.define "client" do |client_config|
    client_config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    client_config.vm.hostname = "client-filebeat-logstash"
    client_config.vm.network "private_network", ip: "172.20.21.29"
    client_config.vm.provision :shell, path: "provision-filebeat-logstash.sh", privileged: false
  end
end
