- name: init
  hosts: all
  become: true
  any_errors_fatal: true
  roles:
    - init.group

- name: config
  hosts: all
  become: true
  any_errors_fatal: true

  tasks:
  - name: get whoami
    shell: whoami
    register: result

  - name: displya whoami
    debug:
      var: result
