version: '2.2'
services:
  # cerebro:
  #   image: lmenezes/cerebro:0.9.4
  #   container_name: cerebro
  #   ports:
  #     - "9000:9000"
  #   command:
  #     - -Dhosts.0.host=http://es7_hot:9200
  #   networks:
  #     - es7net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    environment:
      # use container_name "es7_hot" as url
      # use upper case ENV var name: https://www.elastic.co/guide/en/kibana/current/docker.html#environment-variable-config
      - ELASTICSEARCH_HOSTS=http://es7_hot:9200
    ports:
      - "5601:5601"
    networks:
      - es7net
  es_hot:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es7_hot
    environment:
      - cluster.name=chengdol-es-data-tiers
      - node.name=es7_hot
      - node.roles=master,data_hot,data_content
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_warm,es7_cold
      - cluster.initial_master_nodes=es7_hot,es7_warm,es7_cold
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es7net
  es_warm:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es7_warm
    environment:
      - cluster.name=chengdol-es-data-tiers
      - node.name=es7_warm
      - node.roles=master,data_warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_hot,es7_cold
      - cluster.initial_master_nodes=es7_hot,es7_warm,es7_cold
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data2:/usr/share/elasticsearch/data
    networks:
      - es7net
  es_cold:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es7_cold
    environment:
      - cluster.name=chengdol-es-data-tiers
      - node.name=es7_cold
      - node.roles=master,data_cold
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_hot,es7_warm
      - cluster.initial_master_nodes=es7_hot,es7_warm,es7_cold
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7data3:/usr/share/elasticsearch/data
    networks:
      - es7net

volumes:
  es7data1:
    driver: local
  es7data2:
    driver: local
  es7data3:
    driver: local

networks:
  es7net:
    driver: bridge
